services:
  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: codesearch_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - codesearch-network

  kibana:
    image: kibana:7.8.1
    container_name: codesearch_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - codesearch-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  codesearch-network:
